
package Banco;

import Banco.BancN;
import Banco.Conexao;
import Biblis.Ler;
import javax.swing.JOptionPane;

/**
 *
 * @author junior
 */
public class EditarBanco extends javax.swing.JFrame {

    /** Creates new form EditarBanco */
    public EditarBanco() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Novo Banco");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 160, 270, 30);

        jButton2.setText("Deletar Banco");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 130, 270, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(153, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("Se deletar o Banco de Dados não terá Volta");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 380, 104);

        setSize(new java.awt.Dimension(408, 233));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed


         Object[] options = { "VOu Deletar e Perder todos os Dados", "Sair" };
        if(JOptionPane.OK_OPTION==JOptionPane.showOptionDialog(null,"Deletar ?", "Escolha",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,options, options[0])){

        BancN bc=new BancN();
        bc.conecta();
     bc.executeUpdateL("drop database servicorestaurante");
JOptionPane.showMessageDialog(null, "Banco Deletado");
     System.exit(0);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

String usuario=JOptionPane.showInputDialog("Digite um usuário para o banco de dados ex:root");
String senha=JOptionPane.showInputDialog("Digite a senha do banco de dados");
new Ler().Escrever("dadosbd",usuario+"\n"+senha+"\n");

        BancN banco=new BancN();
banco.conecta();
banco.executeUpdateL("create database servicorestaurante");

        Conexao bc=new Conexao("","","","","");
        

        bc.executeUpdateL("create table cozinha"
                + "(item3 varchar(250),quantidade varchar(200),mesa varchar(250)"
                + ",observacao varchar(250),data varchar(250),garcom varchar(250))");

        
bc.executeUpdateL("create table produtos(item1 varchar(250),"
        + "item2 varchar(250),item3 varchar(250),preco varchar(250))");

    bc.executeUpdateL("create table mesas(mesa varchar(200),estado varchar(200),bloco varchar(200))");
    bc.executeUpdateL("create table garcoms(garcom varchar(200),senha varchar(200))");
   bc.executeUpdateL("create table blocos(bloco varchar(200),circuito varchar(200))");  
        
bc.executeUpdateL("create table pedidos(garcom varchar(250),mesa varchar(250),"
        + "data varchar(200),item3 varchar(250),preco varchar(250),quantidade varchar(250),estado varchar(200),total varchar(100))");
        
bc.executeUpdateL("create table pedidosh(garcom varchar(250),mesa varchar(250),"
        + "data varchar(200),item3 varchar(250),preco varchar(250),quantidade varchar(250),estado varchar(200),total varchar(100))");

 bc.executeUpdateL("insert into mesas (mesa,bloco,estado) values ('000',"
            + "'0','0')");
  bc.executeUpdateL("insert into mesas (mesa,bloco,estado) values ('001',"
            + "'0','0')");
 bc.executeUpdateL("insert into mesas (mesa,bloco,estado) values ('002',"
            + "'0','0')");
   bc.executeUpdateL("insert into garcoms (garcom) values ('joão')");
     bc.executeUpdateL("insert into garcoms (garcom) values ('marcia')");
   bc.executeUpdateL("insert into garcoms (garcom) values ('felipe')");
   
  bc. executeUpdateL("insert into produtos values ('BEBIDAS',"
        + "'SUCOS','LARANJA','3.00') ");
    bc. executeUpdateL("insert into produtos values ('BEBIDAS',"
        + "'SUCOS','MORANGO','3.00') ");
      bc. executeUpdateL("insert into produtos values ('BEBIDAS',"
        + "'SUCOS','UVA','3.00') ");
      
        bc. executeUpdateL("insert into produtos values ('COMIDAS',"
        + "'SALGADOS','COXINHA','3.00') ");
            
        bc. executeUpdateL("insert into produtos values ('COMIDAS',"
        + "'SALGADOS','PASTEL DE QUEIJO','3.00') ");
            
        bc. executeUpdateL("insert into produtos values ('COMIDAS',"
        + "'SALGADOS','PASTEL DE CARNE','3.00') ");
      
  JOptionPane.showMessageDialog(null, "Banco Criado reinicie o Programa");



System.exit(0);






        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarBanco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
